# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dd8bca186f31cc14ae7ff9be58c1b3b59d860fbd8c3aae8891aa6ae7c82db2dfdecd8621026d46dc9bdcb33fa38e5d9dba926ebb76913f3158329469dabe7453

test:
  secret_key_base: d42e118b5ac80bc1b4ff0ab4d154192a529d4ecbc14a1dc8b88f1dbb6c16d9e9b08e4afb227b281a3b94b63543439adc6f9ffb5b95014426f4291df55491c4ec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
